#!/usr/bin/env bash
#
# thanks to Sweets from which I copied some function
# https://github.com/Sweets

CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
CONF_DIR="${CONFIG_HOME}/wal-discord"
OUT_DIR="${HOME}/.cache/wal-discord"

declare -a COLOR_DIR
COLOR_DIR[PYWAL]="${HOME}/.cache/wal/colors.scss"
COLOR_DIR[WPGTK]="${HOME}/.config/wpg/formats/colors.scss"

FORCE_UPDATE=false
# generate BetterDiscord theme
BD_THEME=false
BD_THEME_HEADER='//META{"name":"wal-discord","description":"Generated based on pywal colors","author":"wal-discord","version":"1.0"}*//'

backend=""
out_file="${OUT_DIR}/style.css"

usage() {
    printf "%s\\n" "\
    wal-discord - generate custom discord css files based on pywal colors
-h  Display this help.
-s  Output result to stdout.
-b  Select backend to use.
Supported backends by default are 'wal', 'haishoku'.
It can be any \$value as long as ${CONF_DIR}/backends/\$value.scss exists.
Default is 'wal'.
    "
    exit 1
}

set_backend() {
    [[ ! -r "${CONF_DIR}/backends/${1}.scss" ]] && {
        printf "%s\\n" "Can't find backend $1"
        exit 1
    }
    backend="$1"
}

setup() {
    local exec_path="$0"
    [[ -L "$exec_path" ]] && exec_path="$(readlink "$0")"
    local repo_dir
    repo_dir="$(dirname "$exec_path")"
    [[ ! -d "${repo_dir}/config" ]] && {
        printf "%s\\n" "Can't find needed setup folder: ${repo_dir/config}"
        exit 1
    }
    	printf "Would you like to configure wal-discord for Pywal or WPGTK?\n" 
	read -p "[Pywal/wpgtk]: " init_choice
    	while true
		do
			case "$init_choice" in
			[pP]|[pP][yY][wW][aA][lL])
				set COLOR_DIR=PYWAL
				break ;;
			
			[wW]|[wW][pP][gG][tT][kK])
				set COLOR_DIR=WPGTK
				break ;;
			
			* )
				printf "Invalid choice, defaulting to Pywal.\n" 
				set COLOR_DIR=PYWAL
				break ;;	
		esac
	done

    cp -R "${repo_dir}/config/" "$CONF_DIR"
    ln -sf backends/wal.scss "${CONF_DIR}/backend.scss"
    ln -sf $COLOR_DIR "${CONF_DIR}/colors.scss" 
}

init() {
    OPTIND=1
    while getopts 'hsutb:o:' opt; do
        case "$opt" in
            h) usage;;
            s) out_file="";;
            o) out_file="$OPTARG" ;;
            b) set_backend "$OPTARG" ;;
            u) FORCE_UPDATE=true ;;
            t) BD_THEME=true ;;
            *) ;;
        esac
    done
    
    [[ ! -d "$CONF_DIR" || $FORCE_UPDATE = true ]] && setup
}

main() {
    init "$@"
    
    type -p sassc &>/dev/null || {
        printf "%s\\n" "sassc is not installed and is required"
        exit 1
    }
    
    local master
    master="$(< "${CONF_DIR}/master.scss")"
    [[ ! -z "$backend" ]] && {
        local bp
        bp="backends/${backend}.scss"
        master="${master/backend.scss/$bp}"
    }
    
    local result
    result="$(sassc -I "$CONF_DIR" -s <<< "$master")"
    
    [[ $BD_THEME = true ]] && {
        result="$(printf "${BD_THEME_HEADER}\\n%s" "$result")"
        [[ "$out_file" == "${OUT_DIR}/style.css" && -d "${CONFIG_HOME}/BetterDiscord/themes" ]] && {
            out_file="${CONFIG_HOME}/BetterDiscord/themes/wal_discord.theme.css"
        }
    }
    
    if [[ ! -z "$out_file" ]]; then
	    mkdir -p "$(dirname "$out_file")"
        printf "%s\\n" "$result" > "$out_file"
    else
        printf "%s\\n" "$result"
    fi
    
}

main "$@"
